// All the different incident categories that were returned by a GROUP BY 'incident_category' call to the back end API>
const INCIDENT_CATEGORIES = [
    "All",
    "Arson",
    "Assault",
    "Burglary",
    "Case Closure",
    "Civil Sidewalks",
    "Courtesy Report",
    "Disorderly Conduct",
    "Drug Offense",
    "Drug Violation",
    "Embezzlement",
    "Fire Report",
    "Forgery And Counterfeiting",
    "Fraud",
    "Gambling",
    "Homicide",
    "Human Trafficking (A), Commercial Sex Acts",
    "Human Trafficking (B), Involuntary Servitude",
    "Human Trafficking, Commercial Sex Acts",
    "Larceny Theft",
    "Liquor Laws",
    "Lost Property",
    "Malicious Mischief",
    "Miscellaneous Investigation",
    "Missing Person",
    "Motor Vehicle Theft",
    "Motor Vehicle Theft?",
    "Non-Criminal",
    "Offences Against The Family And Children",
    "Other",
    "Other Miscellaneous",
    "Other Offenses",
    "Prostitution",
    "Rape",
    "Recovered Vehicle",
    "Robbery",
    "Sex Offense",
    "Stolen Property",
    "Suicide",
    "Suspicious",
    "Suspicious Occ",
    "Traffic Collision",
    "Traffic Violation Arrest",
    "Vandalism",
    "Vehicle Impounded",
    "Vehicle Misplaced",
    "Warrant",
    "Weapons Carrying Etc",
    "Weapons Offence",
    "Weapons Offense"
];

export {INCIDENT_CATEGORIES};